# Generated by Django 4.1.13 on 2023-12-04 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientType',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('ingredient_id', models.CharField(default='aa2e6576-e331-4dc3-8f3c-b5ebb0ed5435', editable=False, max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='MenuIngredient',
            fields=[
                ('ingredient_id', models.CharField(default='e1e0fe42-9a39-49da-8a67-5c888df2af3e', editable=False, max_length=100, primary_key=True, serialize=False)),
                ('item_id', models.CharField(default='d99d058e-09b9-4410-a837-5eb7e5a03b72', editable=False, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('item_id', models.CharField(default='3029ca4d-d1b2-4261-84de-9ea27b3564dc', editable=False, max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('alergies', models.JSONField()),
            ],
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
        migrations.DeleteModel(
            name='MenuItemIngredient',
        ),
        migrations.AlterField(
            model_name='order',
            name='item',
            field=models.CharField(default='f5e46d37-a451-4fba-87de-3ceb78c3dc4a', editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='f9d9f4a9-2695-4222-8149-57392979d712', editable=False, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='payment',
            name='order',
            field=models.CharField(default='41f31d79-17d1-4dbf-bbeb-6a445d3ba42a', editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(default='239fcc6e-56a2-4b0b-9ba7-964cf18e64bb', editable=False, max_length=100, primary_key=True, serialize=False),
        ),
    ]
