# Generated by Django 4.1.13 on 2023-12-04 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0002_ingredienttype_menuingredient_menuitem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredienttype',
            name='ingredient_id',
            field=models.CharField(default='e1b99a0e-78be-43c7-8bb0-8524613887f7', editable=False, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='menuingredient',
            name='ingredient_id',
            field=models.CharField(default='5ddf2b14-6113-4a99-9a61-a362aa7bf513', editable=False, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='menuingredient',
            name='item_id',
            field=models.CharField(default='c6682eff-a149-498d-be2e-d5a3ad9dcd03', editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='item_id',
            field=models.CharField(default='36d257c8-67c6-456c-b0f7-2deeda8097a9', editable=False, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='item',
            field=models.CharField(default='4c8b168d-378b-4f0a-865a-6c792a7a3b71', editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='9114cdee-5c99-422f-8b7c-cc226bd0b14b', editable=False, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='payment',
            name='order',
            field=models.CharField(default='e3829472-3c9b-486e-af2a-405f682f02a9', editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(default='ffc94da3-a9a7-4091-b7f6-544295d311ff', editable=False, max_length=100, primary_key=True, serialize=False),
        ),
    ]
