# Generated by Django 4.1.13 on 2023-12-04 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0003_alter_ingredienttype_ingredient_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredienttype',
            name='ingredient_id',
            field=models.CharField(default='1b5986f8-ca03-44bb-be02-6339b60677a2', editable=False, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='menuingredient',
            name='ingredient_id',
            field=models.CharField(default='48017e91-3853-4f65-ae3c-45dc2d051267', editable=False, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='menuingredient',
            name='item_id',
            field=models.CharField(default='0a1fdd98-d276-4b67-8bdb-181608f0a704', editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='item_id',
            field=models.CharField(default='316c1cc4-e9fb-4f16-be5f-cbfc6cda486a', editable=False, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='item',
            field=models.CharField(default='97d38869-dc6e-44b9-a25b-f85a2e549b4f', editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='2f5b3a6a-e629-4c1a-a278-9d1a6d60f742', editable=False, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='payment',
            name='order',
            field=models.CharField(default='5508b816-b1ea-40d2-9e72-560e78de7314', editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(default='70d06061-135b-4a13-8686-9f456fb317b4', editable=False, max_length=100, primary_key=True, serialize=False),
        ),
    ]
