# Generated by Django 4.1.13 on 2023-12-04 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0004_alter_ingredienttype_ingredient_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredienttype',
            name='ingredient_id',
            field=models.CharField(default='f0eeaaae-55c4-4489-becc-f8633dc1985b', editable=False, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='menuingredient',
            name='ingredient_id',
            field=models.CharField(default='793d687f-1007-4901-91e0-2a085c21cb45', editable=False, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='menuingredient',
            name='item_id',
            field=models.CharField(default='9a48930b-b343-4db6-abd9-c3dc33123716', editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='item_id',
            field=models.CharField(default='918039bb-1fba-4367-b07a-f0da658aeb3a', editable=False, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='item',
            field=models.CharField(default='bc748d5e-570d-419d-aebb-03c2be25dcce', editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='73383c30-52f3-4539-abac-787da1e1a8cc', editable=False, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='payment',
            name='order',
            field=models.CharField(default='40999043-175a-49cb-87db-8e1d9cd942f5', editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(default='0393a5fe-ef6c-4fe1-9c4c-c957721ef23d', editable=False, max_length=100, primary_key=True, serialize=False),
        ),
    ]
