# Generated by Django 4.1.13 on 2023-12-04 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0005_alter_ingredienttype_ingredient_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredienttype',
            name='ingredient_id',
            field=models.CharField(default='b81843cf-663f-4f86-8639-5f673dfe9cdd', editable=False, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='menuingredient',
            name='ingredient_id',
            field=models.CharField(default='a68f62d6-2d3a-438c-8e38-082ab1fb6b16', editable=False, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='menuingredient',
            name='item_id',
            field=models.CharField(default='5362464f-7da0-4c40-9ff6-61e457a3480d', editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='item_id',
            field=models.CharField(default='0ac26f19-5276-4180-9ac9-1d2456624d78', editable=False, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='item',
            field=models.CharField(default='83502788-a393-4bbc-9140-9c3e716c40ce', editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='19cf3f1b-fbc1-4ccd-933a-fa37b245cd2e', editable=False, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='payment',
            name='order',
            field=models.CharField(default='4592b244-6baa-4132-8b80-762dfc2e0813', editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(default='e4cffc5a-c131-470c-803d-b6cf41daadf7', editable=False, max_length=100, primary_key=True, serialize=False),
        ),
    ]
