# Generated by Django 4.1.13 on 2023-12-04 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0006_alter_ingredienttype_ingredient_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredienttype',
            name='ingredient_id',
            field=models.CharField(default='2d7ceb66-2330-4e61-84d6-c38c39512840', editable=False, max_length=10000, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='menuingredient',
            name='ingredient_id',
            field=models.CharField(default='417953e1-4d48-4fbf-87da-edd8d8ceed69', editable=False, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='menuingredient',
            name='item_id',
            field=models.CharField(default='3883562a-bfab-425f-86bc-3f783e5de491', editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='item_id',
            field=models.CharField(default='65afd340-f1fc-4a9a-b742-2842da84fb7b', editable=False, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='item',
            field=models.CharField(default='33e2141a-b3a1-4985-b3d1-368150abc0d7', editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='ca0b3d8d-f7a1-4542-9766-7d2ea5b74f19', editable=False, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='payment',
            name='order',
            field=models.CharField(default='249ba9e4-7b87-4749-a1ca-de9377c1e4ee', editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(default='a92275fc-977d-4295-bc89-f86c9c2e492a', editable=False, max_length=100, primary_key=True, serialize=False),
        ),
    ]
